---
title: "test_7_6_2022"
author: "Bridget Knapp"
output: html_document
params:
      data_channel_is: "Lifestyle"
---

```{r include=FALSE}
knitr::opts_chunk$set(fig.path = "./images/")


# title: "ST558 Porject 1: Part 2 Test"
# author: "Bridget Knapp and Chien-Lan Hsueh"
# institute: Online Statistics Master Program, NCSU
# date: "`r Sys.Date()`"
# output:
#   html_notebook:
#     theme: cerulean
#     highlight: haddock
#     code_folding: none
#   html_document:
#     df_print: paged

```


## Data

> Use a relative path to import the data. Subset the data to work on the data channel of interest.
>
> This section should be done by whoever can get to it first.


## Start here...

```{r render, eval = FALSE}
#this is the code I used to render this document before I committed changes to the repository
rmarkdown::render("part 2 - data.Rmd",
                  output_format = "github_document",
                  output_options = list(
                    toc = TRUE,
                    html_preview=FALSE) 
)

```

```{r 6:20_7_6_2022, eval = FALSE}
#In order to make one html output for each news channel, run this code in the console first
channel_list <- c("Lifestyle", "Entertainment", "Business", "Social_Media", "Tech", "World")
output_file <- paste0(channel_list,".html")
params <- lapply(channel_list, FUN = function(x){list(data_channel_is=x)})
reports <- tibble(output_file,params)

library(rmarkdown)
apply(reports, MARGIN = 1,
      FUN = function(x){
        render(input="C://Users//Bridget//OneDrive//R_Scripts//test_7_6_2022.Rmd",output_file = x[[1]], params = x[[2]])
      })
```


```{r 8:36 7_5_2022,message=FALSE,warning=FALSE}
library(tidyverse)
library(readr)
data<-read_csv("../ST558-Project2/data/OnlineNewsPopularity.csv")
head(data)
```

Subset the data to work on the data channel of interest.

```{r 8:49_7_5_2022}
#This code processes the data. It removes excess data_channel_is_ columns and filters the column we want so that it only includes values of 1. For example, if you want the "Lifestyle" data, this function will remove the other data channel columns (Entertainment, Business, Social Media, Tech, and World) and filter it so that it only includes data where data_channel_is_lifestyle == 1.

library(tidyverse)
library(readr)
library(shiny)
data<-read_csv("C://Users//Bridget//OneDrive//R_Scripts//repos//ST558-Project2//data//OnlineNewsPopularity.csv")
head(data)
channel <- params$data_channel_is
channel

subset_data <- function(channel_of_interest){
  if(channel_of_interest=="Lifestyle"){
    new_data = subset(data, select = -c(data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world))
    new_data <- filter(new_data, data_channel_is_lifestyle == 1)
  }
  if(channel_of_interest=="Entertainment"){
    new_data = subset(data, select = -c(data_channel_is_lifestyle,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world) )
    new_data <- filter(new_data, data_channel_is_entertainment == 1)
  }
   if(channel_of_interest=="Business"){
    new_data = subset(data, select = -c(data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world) )
    new_data <- filter(new_data, data_channel_is_bus == 1)
   }
   if(channel_of_interest=="Social_Media"){
    new_data = subset(data, select = -c(data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_tech,data_channel_is_world) )
    new_data <- filter(new_data, data_channel_is_socmed == 1)
   }
   if(channel_of_interest=="Tech"){
    new_data = subset(data, select = -c(data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_world) )
    new_data <- filter(new_data, data_channel_is_tech == 1)
   }
   if(channel_of_interest=="World"){
    new_data = subset(data, select = -c(data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech) )
    new_data <- filter(new_data, data_channel_is_world == 1)
  }
  return(new_data)
}

channel_data <- subset_data(channel)
head(channel_data)

# Lifestyle_data <- subset_data(channel_of_interest="Lifestyle")
# head(Lifestyle_data)
# dim(Lifestyle_data)
# 
# Entertainment_data <- subset_data(channel_of_interest="Entertainment")
# head(Entertainment_data)
# dim(Entertainment_data)
# 
# Business_data <- subset_data(channel_of_interest="Business")
# head(Business_data)
# dim(Business_data)
# 
# Social_Media_data <- subset_data(channel_of_interest="Social_Media")
# head(Social_Media_data)
# dim(Social_Media_data)
# 
# Tech_data <- subset_data(channel_of_interest="Tech")
# head(Tech_data)
# dim(Tech_data)
# 
# World_data <- subset_data(channel_of_interest="World")
# head(World_data)
# dim(World_data)

```
