---
title: "ST558 Porject 1: Part 1"
author: "Bridget Knapp and Chien-Lan Hsueh"
institute: Online Statistics Master Program, NCSU
date: "`r Sys.Date()`"
output:
  html_notebook:
    theme: cerulean
    highlight: haddock
    code_folding: none
  html_document:
    df_print: paged
---



## Online News Popularity

In this project, we study the [Online News Popularity Data Set](https://archive.ics.uci.edu/ml/datasets/Online+News+Popularity) and model the number of shares of a new articles by the attributes including

- Type, or channel, of news (Lifestyle, Entertainment, Business, Social Media, Tech, or World)
- Number of links, images, and videos
- Minimum, maximum, and average number of shares for the worst, best, and average keyword 
- When the article was published (Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, or a weekend)?
- Minimum, maximum, and average polarity of positive and negative words in the article
- Number of words in the title and in the content

## Purpose
The purpose of this study is to summarize the data and to predict the number of shares based on chosen aspects of interest. 

## Workflow
The workflow includes:

- Load data and split training/test set (70%/30%)
- For each news channel:
  - EDA on train set
  - Train and select model with cross validation
  - Compare model performance

The supervised learning algorithms we use to create models are linear regression and ensemble models (random forests and boosted tree). We also automate the generation of the analysis reports.




